### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/uiua#1]
Overall documentation for building an Exercism track lives at https://exercism.org/docs/building/tracks/new

This issue helps keep track of the tasks you're working on towards launching this track.

The next steps are:

- [x] [Join our community](https://exercism.org/docs/building/tracks/new/join-our-community)
- [x] [Select programming language variant](https://exercism.org/docs/building/tracks/new/select-programming-language-variant) (if applicable)
- [x] [Select testing framework](https://exercism.org/docs/building/tracks/new/select-testing-framework)
- [x] [Add the first exercise](https://exercism.org/docs/building/tracks/new/add-first-exercise)
- [x] [Setup Continuous Integration](https://exercism.org/docs/building/tracks/new/setup-continuous-integration)
- [x] [Add initial exercises](https://exercism.org/docs/building/tracks/new/add-initial-exercises)
- [x] [Build test runner](https://exercism.org/docs/building/tracks/new/build-test-runner)
- [x] [Configure tooling](https://exercism.org/docs/building/tracks/new/configure-tooling)
  - [x] [Lines of Code Counter](https://exercism.org/docs/building/tooling/lines-of-code-counter)
  - [x] [Snippet Extractor](https://exercism.org/docs/building/tooling/snippet-extractor)
  - [x] [Exercism CLI](https://exercism.org/docs/building/tooling/cli)
- [x] [Prepare for launch](https://exercism.org/docs/building/tracks/new/prepare-for-launch)
  - [x] [Request Track Icon](https://exercism.org/docs/building/tracks/new/prepare-for-launch#h-request-track-icon)
  - [x] [Add Track Docs](https://exercism.org/docs/building/tracks/new/prepare-for-launch#h-add-track-docs)
  - [x] [Add Exercise Docs](https://exercism.org/docs/building/tracks/new/prepare-for-launch#h-add-exercise-docs)
  - [x] [Add Code snippet](https://exercism.org/docs/building/tracks/new/prepare-for-launch#h-add-code-snippet)
  - [x] [Update metadata](https://exercism.org/docs/building/tracks/new/prepare-for-launch#h-update-metadata)
- [ ] [Test track](https://exercism.org/docs/building/tracks/new/test-track)
- [ ] [Find Maintainers](https://exercism.org/docs/building/tracks/new/find-maintainers)
- [ ] [Launch!](https://exercism.org/docs/building/tracks/new/launch)
- [ ] [Enable syntax highlighting](https://exercism.org/docs/building/tracks/new/enable-syntax-highlighting)
  - [x] [Static syntax highlighting](https://exercism.org/docs/building/tracks/new/syntax-highlighting/static) (optional)
  - [x] [Dynamic syntax highlighting](https://exercism.org/docs/building/tracks/new/syntax-highlighting/dynamic) (optional)
- [ ] [Implement additional tooling](https://exercism.org/docs/building/tracks/new/implement-tooling)
  - [ ] [Build Representer](https://exercism.org/docs/building/tooling/representers) (optional)
  - [ ] [Build Analyzer](https://exercism.org/docs/building/tooling/analyzers) (optional)
  - [ ] [Build Test Generator](https://exercism.org/docs/building/tooling/test-generators) (optional)
- [ ] [Prepare for open source contributions from strangers](https://exercism.org/docs/building/tracks/new/prepare-for-contributions)

Once you've finished a task, you can check them in this list.

## Questions

Please ask if you have any questions or if anything is confusing!

**Comment by vaeng** [comment]
I added a PR for the exercism CLI: https://github.com/exercism/cli/pull/1183

**Comment by ErikSchierboom** [comment]
@vaeng I'll do the lines of code counter PR

**Comment by ErikSchierboom** [comment]
I'll do the metadata PR too

**Comment by vaeng** [comment]
icon was requested under: https://github.com/exercism/website-icons/issues/184

**Comment by vaeng** [comment]
I'll look into syntax highlighting

**Comment by ErikSchierboom** [comment]
Lines of code counter has been updated

**Comment by ErikSchierboom** [comment]
Opened a PR for adding key features: https://github.com/exercism/uiua/pull/41

**Comment by ErikSchierboom** [comment]
@vaeng I've added the track to the DB which means that maintainers could start testing the track at https://exercism.org/tracks/uiua. Was there anything we need to do before they can test? I know you were looking at the syntax highlighting but that can happen in parallel.

**Comment by vaeng** [comment]
Wow, that was speedy progress! With more than 20 exercises implemented and more to come, it is a promising start.
Testing the website does not give me the web-editor. Is there something else we've got to change for that to work? I would not release it for testing without an online edtior.

Syntax highlighting would be great, but I have no idea where to start and expected a more streamlined process. So I don't mind if someone more experienced would take over.

**Comment by vaeng** [comment]
I asked Jeremy for the terraforming and it should be done by now. I'll do a PR for the test runner activation.

**Comment by vaeng** [comment]
Should we clean up the repository by auto-deleting merged branches and remove those we have merged so far?

**Comment by ErikSchierboom** [comment]
Yes please

**Comment by ErikSchierboom** [comment]
I removed the old branches. How do I enable auto-deleting them?

**Comment by vaeng** [comment]
> I removed the old branches. How do I enable auto-deleting them?

It's in the settings: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

**Comment by ErikSchierboom** [comment]
Thanks! I've checked that settings.

Highlightjs support is coming: https://github.com/exercism/website/pull/7161

**Comment by vaeng** [comment]
> An error occurred while running your tests. This might mean that there was an issue in our infrastructure, or it might mean that you have something in your code that's causing our systems to break.
Please check your code, and if nothing seems to be wrong, try running the tests again.

I just tried the hello world exercise in the online-editor and there is something amiss. Did I set the time limit too low?

**Comment by ErikSchierboom** [comment]
> Did I set the time limit too low?

No, that can't be it, as that's only cosmetic. I think I just need ti redeploy.

**Comment by ErikSchierboom** [comment]
Try again!

**Comment by ErikSchierboom** [comment]
Next up: a codemirror plugin https://github.com/exercism/codemirror-lang-uiua

**Comment by vaeng** [comment]
> Try again!

![Screenshot 2024-11-19 205854](https://github.com/user-attachments/assets/8f98761d-2735-49b9-8383-b8979b18add6)

**Comment by vaeng** [comment]
Static syntax highlighting looks nice. Thanks :)

**Comment by vaeng** [comment]
The default icon is correct in most places but it fails in the recent tracks preview 😕 

![image](https://github.com/user-attachments/assets/0598775f-99ee-4827-a4a6-97bf05173fcc)

**Comment by ErikSchierboom** [comment]
That's something to post on the forum if you please.

**Comment by vaeng** [comment]
Should we go public when the codemirror work is done and the icon is added?

**Comment by ErikSchierboom** [comment]
I think so yes! I'll work on the codemirrror stuff tomorrow

**Comment by ErikSchierboom** [comment]
https://github.com/exercism/website/pull/7167 (should be merged soon)

**Comment by ErikSchierboom** [comment]
![image](https://github.com/user-attachments/assets/074308ff-80d6-43c1-be90-0918c9d663ec)
🥳

**Comment by ErikSchierboom** [comment]
Do we want to launch the test runner with the latest stable version (`0.13`) or do we want to use the latest dev version? I'm asking because I've found myself using [Uiua pad](https://www.uiua.org/pad) a lot and that runs on the latest dev version.

**Comment by vaeng** [comment]
As we promote the padlet in the docs, I would vote for their latest version.

**Comment by ErikSchierboom** [comment]
https://github.com/exercism/uiua-test-runner/pull/4

**Comment by vaeng** [comment]
The icon is live. Should we set the trigger and release this beast?

**Comment by ErikSchierboom** [comment]
Yes!

**Comment by vaeng** [comment]
Nice. Let's close this issue and celebrate. Three weeks for a new track, glorious. Thanks for the ride Erik.
